# Generated by Django 3.2 on 2022-05-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
