# Generated by Django 3.2.13 on 2022-07-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loanmodel_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanmodel',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='debtmodel',
            name='payment_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
