# Generated by Django 3.2 on 2022-06-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customusermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='national_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
