# Generated by Django 3.2 on 2022-06-11 16:41

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customusermodel_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=11, region=None, unique=True),
        ),
    ]
