# Generated by Django 3.2 on 2022-06-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customusermodel_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='condition',
            field=models.BooleanField(default=False),
        ),
    ]
