# Generated by Django 3.2 on 2022-06-09 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extra', '0002_alter_likecomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarck',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
